name: loja_virtual
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_functions: ^0.7.2
  firebase_core: ^0.5.3
  cpf_cnpj_validator: ^1.0.5
  flutter_facebook_login: ^3.0.0
  url_launcher: ^5.7.10
  flutter_svg: ^0.18.0
  map_launcher: ^1.0.0
  screenshot: ^0.2.0
  gallery_saver: ^2.0.1
  flutter_signin_button: ^1.1.0
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.4+1
  cloud_firestore: ^0.14.4
  firebase_storage: ^5.2.0
  uuid: ^2.2.2
  provider: ^4.3.2+3
  carousel_pro: ^1.0.0
  firebase_messaging: ^7.0.3
  transparent_image: ^1.0.0
  flutter_staggered_grid_view: ^0.3.2
  alphabet_list_scroll_view: ^1.0.6
  image_picker: ^0.6.7+17
  image_cropper: ^1.3.1
  dio: ^3.0.10
  flushbar: ^1.10.4
  keyboard_actions: ^3.3.1+1
  brasil_fields: ^0.6.0
  credit_card_type_detector: ^1.1.0
  geolocator: ^6.1.13
  sliding_up_panel: ^1.0.2
  faker: ^1.2.1
  mask_text_input_formatter: ^1.1.0
  flip_card: ^0.4.4
  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
